### ISSUE TITLE
cannot import convertcloud in ubuntu 14.04

### ISSUE THREAD

**Issue by ljc19800331** [SintefRaufossManufacturing/convertcloud#4]
Hello,

I install the convertcloud in ubuntu 14.04 but I got the following error:

import convertcloud
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/convertcloud/__init__.py", line 1, in <module>
    # -*- coding: utf-8 -*-
ImportError: No module named convertcloud

**Comment by alvcap** [comment]
Hi!

Try with the current version. Does the issue still persist?
